### ISSUE TITLE
How I can get the current Circuit Breaker using Circuit Breaker annotation?

### ISSUE THREAD

**Issue by silviobuss** [resilience4j/resilience4j-spring-boot2-demo#10]
How I can get the current Circuit Breaker using Circuit Breaker annotation?

I tried this to get and reset the circuit breaker:
(https://resilience4j.readme.io/docs/examples -> Reset CircuitBreaker)

```
   CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults(BACKEND_A);
   circuitBreaker.reset();
```

And this:
- This returns a empty list.
```
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
circuitBreakerRegistry.getAllCircuitBreakers();

```

			
But I have some issues with one scenario:

- When I have two test in the same suite I need to that one test does not affect others.

Example:

cfg -> ringBufferSizeInClosedState: 5

```
  @Test
    public void shouldStayClosedCircuitBreaker() {
        Stream.rangeClosed(1, 4).forEach((count) -> produceFailure(BACKEND_A));
        checkHealthStatus(BACKEND_A + "CircuitBreaker", Status.UP);
    }

    @Test
    public void shouldStayClosedCircuitBreaker2() throws InterruptedException {
        Stream.rangeClosed(1, 4).forEach((count) -> produceFailure(BACKEND_A));
        checkHealthStatus(BACKEND_A + "CircuitBreaker", Status.UP);
    }
```
	
Someone can help me?

**Comment by RobWin** [comment]
Hi,

what type of test do you want to write? A unit test to test the functionality of resilience4j-circuitbreaker?

You can always just inject (autowire) a `CircuitBreakerRegistry` into your class

```
@Autowired
	private CircuitBreakerRegistry registry;
```

and then do `registry.circuitBreaker("name").reset()`

**Comment by silviobuss** [comment]
After some time investigating I found the problem. It was only my Intellij Idea that was referring to my old version (0.12) of resilience4j. (Oh God)

In 0.16 version,  the CircuitBreakerRegistry inject works fine! 

Thanks!
