### ISSUE TITLE
Have an example using pom.xml?

### ISSUE THREAD

**Issue by hhs9102** [resilience4j/resilience4j-spring-boot2-demo#15]
I am using pom.xml

How can I execute the fallback method via annotation?

Do you have an example without using application.yml?

Is it possible?

**Comment by RobWin** [comment]
Hi, 
there is a demo for Spring Boot 2. Did you have a look at it?

**Comment by hhs9102** [comment]
Thank you very much for the answer.

Yes I did

But my fallback method did not run.

When I printed out the beans list of the applicationContext, I noticed that the CircuitBreaker classes are not registered as beans, unlike the demo project.

Can you advise classes such as circuitBreakerAspect, circuitBreakerEndpoint, circuitBreakerRegistry to be registered as beans?

===========
String[] beans = applicationContext.getBeanDefinitionNames();
            Arrays.sort(beans);
            for(String bean : beans){
            if(bean.toUpperCase().indexOf("CIRCUITBREAKER") > -1){
                System.out.println(bean);
            }
        }
===========output===========
RCircuitBreakerController
circuitBreakerController
org.springframework.cloud.netflix.hystrix.HystrixCircuitBreakerConfiguration

**Comment by hhs9102** [comment]
pom.xml

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>0.17.0</version>
        </dependency>

Thank you...!
