### ISSUE TITLE
What is the minimum string boot2 version to apply?

### ISSUE THREAD

**Issue by hhs9102** [resilience4j/resilience4j-spring-boot2-demo#17]
1. Does it not work with spring boot 2.0.6 version?
In version 2.0.6, the HealthIndicatorRegistry class does not exist and an error occurs at runtime.

2. Can I handle business logic by receiving a state change event from CircuitBreaker?
How can I do it?

**Comment by RobWin** [comment]
Sry, I didn't see this issue.
Could you please open further issues in the core project.

True, I didn't notice that the `HealthIndicatorRegistry` is only available since `2.1.0`.

**Comment by RobWin** [comment]
But we removed the usage of the  `HealthIndicatorRegistry` in the latest release.
The  `HealthIndicatorRegistry` should not be used anymore in resilience4j `1.1.0`.

**Comment by RobWin** [comment]
Answer for 2)
You can create a Bean and inject the CircuitBreakerRegistry. 
In this bean you can add event handlers to your CircuitBreakers.

**Comment by hhs9102** [comment]
Thank you!

**Comment by RobWin** [comment]
Did it help you? Can I close the issue?

**Comment by hhs9102** [comment]
Yes it was helpful.
You can also close the issue.
Thank you!

**Comment by hhs9102** [comment]
Yes it was helpful.
You can also close the issue.
Thank you!
