### ISSUE TITLE
Check for the retry attempts

### ISSUE THREAD

**Issue by BijuSs** [resilience4j/resilience4j-spring-boot2-demo#26]
Hi,

I am using the resilience retry functionality for my project and it is working well. That is whenever the call fails, the retry is performed and routes to fall back method when the retries are done. But I need to check the retry attempt count in order to achieve a functionality. Could you please help me on this? I didn't find any documentation regarding this.

@RobWin 

Thanks
Biju

**Comment by RobWin** [comment]
Hi,
what do you mean by "I need to check the retry attempt count in order to achieve a functionality"? 
In the fallback method you need to know the retry attempt count?

**Comment by BijuSs** [comment]
Thanks for your reply @RobWin 

What i need to achieve is that when the first retry is attempted I need to let the customer know that the application is down and it is going for retry. The fallback method is executed only after all the retries are done, right?

I have a method which is calling the external service, in that method i need to check whether the call is a retry one and the also whether the attempt is first one, if so i need to send a notification.
Hope this clarifies. 

Thanks

**Comment by BijuSs** [comment]
@RobWin 

Could you please help me on this?

**Comment by RobWin** [comment]
That's not possible. I fear you have to implement your own custom retry logic.
