### ISSUE TITLE
Log: Reactor and RxJava2

### ISSUE THREAD

**Issue by MMaalej** [resilience4j/resilience4j-spring-boot2-demo#37]
Hi,

I see this two entries in the log:
RxJava2 related Aspect extensions are not activated, because RxJava2 is not on the classpath.
Reactor related Aspect extensions are not activated because Reactor is not on the classpath.

I don't know what I'm doing wrong!

I have a Maven-Project with this dependency:
	   	<dependency>
    		<groupId>io.github.resilience4j</groupId>
  			<artifactId>resilience4j-spring-boot2</artifactId>
  			<version>1.3.1</version>
    	         </dependency>
I use Java 1.8 and Spring boot Version 2.2.6.

Thanks,
Maalej

**Comment by RobWin** [comment]
Nothing is wrong. It's just telling you that are not using `resilience4j-reactor` or `resilience4j-rxjava2` and thus the return types are not supported.

**Comment by MMaalej** [comment]
How can I use resilience4j-reactor or resilience4j-rxjava2? just import it as dependency?
How can I delete this entries in the log?

Thanks, Maalej

**Comment by RobWin** [comment]
You can't delete the entries in the log.
If you want to use Spring Reactor, then yes just import as a dependency.

**Comment by MMaalej** [comment]
Thanks.
i don't find the dependencies, could you please mention the dependencies for reactor und RxJava2 .

**Comment by RobWin** [comment]
Where did you look? Below  your carpet ? :) 

https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-reactor
