### ISSUE TITLE
How to change the config resilience4j from applicaton.yml to file application.properites

### ISSUE THREAD

**Issue by dunguchi** [resilience4j/resilience4j-spring-boot2-demo#39]
my project right now don't use applicaton.yml. I am using application.properites file. How can i config it also maybe we have another way to config resilience4j without applicaton.yml, application.properites. May i config with Java.Class. Thanks!

**Comment by silviobuss** [comment]
Hi,

I have some projects (privates) that use resilience4j with application.properties.
The idea is the same of model with application.yml file. This is an example:

![image](https://user-images.githubusercontent.com/51520066/86469008-ef49bb80-bd0e-11ea-9056-2e27ff0108e9.png)

Hope this helps :)

**Comment by dunguchi** [comment]
Thanks @silviobuss for your help. I have a question. Did you use java bean for config resilience4j to config to replace applicaton.yml or application.properites. Thank you!
