### ISSUE TITLE
Broken tests (Java 11)

### ISSUE THREAD

**Issue by silviobuss** [resilience4j/resilience4j-spring-boot2-demo#41]
Hi,

Several tests are broken when running this demo with java 11 (LTS) and gradle 6.6.

![image](https://user-images.githubusercontent.com/51520066/90899831-e3898580-e39e-11ea-97c0-bf431ea6476f.png)

Debugging the code, the problem is due to the test asserts of the metric generated:

Generated metric (application):
_resilience4j_retry_calls_total {application = "resilience4j-demo", kind = "failed_with_retry", name = "backendB",} 1.0_

Assert of a retry test (for example, ReactiveRetryTest#backendBshouldRetryThreeTimes#checkMetrics)
_resilience4j_retry_calls_total {application = "resilience4j-demo", kind = "failed_with_retry", name = "backendB",} 1,0_

The comma that was inserted by **String.format ("%. 1f", count)** in L.36 (AbstractRetryTest) to do the validations is the problem in this case, to fix it, I just remove this String.format by only the **count** value.

I saw that this was added by @dlsrb6342 for "Fix failed tests" on 23/04/2020. Should I do a PR?

**Comment by dlsrb6342** [comment]
Hi @silviobuss 
Thank you for reporting. Could you submit a PR?

**Comment by silviobuss** [comment]
Hi @dlsrb6342 

I tested with Java 8 and I had the same issue.

![image](https://user-images.githubusercontent.com/51520066/91060084-e84d7400-e600-11ea-988d-6eab0e5a84f3.png)

I find it strange because on Travis CI it's Ok.

**Comment by silviobuss** [comment]
PR with the fix https://github.com/resilience4j/resilience4j-spring-boot2-demo/pull/42

**Comment by RobWin** [comment]
thx
