### ISSUE TITLE
Error in AbstractIntegrationTest

### ISSUE THREAD

**Issue by spandit91** [resilience4j/resilience4j-spring-boot2-demo#45]
Getting error in line, @RunWith(SpringRunner.class)
It says :Type mismatch: cannot convert from Class<SpringRunner> to Class<? extends Runner>
 
For junit using the below dependency:

<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.4</version>
    <scope>test</scope>
</dependency>

**Comment by RobWin** [comment]
How is this related to Resilience4j?

**Comment by RobWin** [comment]
Tests are passing on our CI pipeline. Must be a local issue. Is it related to #40

**Comment by spandit91** [comment]
Hi RobWin,
I had commented that line //@RunWith(SpringRunner.class), it is was related to the tests so thought to get in touch.

Thanks!
