### ISSUE TITLE
Not able to fetch data from some endpoints

### ISSUE THREAD

**Issue by kavinkumarc** [resilience4j/resilience4j-spring-boot2-demo#55]
http://localhost:9080/actuator/   works well for me. But ""http://localhost:9080/actuator/hystrixstreamcircuitbreakerevents" is not returning any data. It is just loading for long time. I have attached the images also
<img width="1392" alt="Screenshot 2021-05-10 at 2 01 00 PM" src="https://user-images.githubusercontent.com/77623860/117630159-89348d00-b198-11eb-8136-63222164ffe7.png">
<img width="1392" alt="Screenshot 2021-05-10 at 2 01 18 PM" src="https://user-images.githubusercontent.com/77623860/117630185-8df94100-b198-11eb-9cb0-fe827febb9d3.png">

**Comment by RobWin** [comment]
It's an Server-Sent Events (SSE) endpoint, you have to generate some data by invoking some endpoints `/backendA/success`
