### ISSUE TITLE
Wrong name in circuit breaker properties in application.yml

### ISSUE THREAD

**Issue by debop** [resilience4j/resilience4j-spring-boot2-demo#6]
circuit breaker configuration property key 

`waitDurationInOpenState` not exists
should change to `waitDurationInOpenStateMillis`

then circuit breaker test is worked

**Comment by RobWin** [comment]
Yes, that's a change which happened in 0.16.0-SNAPSHOT when we merged the config classes from Spring Boot and Ratpack. I think we will revert it to `waitDurationInOpenState`.

**Comment by RobWin** [comment]
Should be fixed now with the latest SNAPSHOT version.
