### ISSUE TITLE
Unable to See Resilience4j Metrics in Prometheus Endpoint

### ISSUE THREAD

**Issue by kushanihansika** [resilience4j/resilience4j-spring-boot2-demo#76]
I integrated Resilience4j into my Spring Boot application, but I can't seem to retrieve Resilience4j-specific metrics at the Prometheus endpoint. Here's my setup:

plugins {
    id 'java'
    id 'groovy'
    id 'jacoco'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
    id "org.sonarqube" version "4.0.0.2929"
}

dependencies {
    implementation 'io.github.resilience4j:resilience4j-spring-boot2'
    implementation 'io.github.resilience4j:resilience4j-micrometer:2.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

resilience4j:
  circuitbreaker:
    instances:
      backendService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 100ms
        recordExceptions:
          - java.io.IOException
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
  timelimiter:
    instances:
      backendService:
        timeout-duration: 100ms
  metrics:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

**Comment by RobWin** [comment]
Hi,
did you also add something like `micrometer-registry-prometheus` ?

**Comment by kushanihansika** [comment]
Thank you for your response! Since my Spring Boot version is 3.0.4, I had to include the following dependencies to make it work:

	implementation 'io.github.resilience4j:resilience4j-bulkhead:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-circuitbreaker:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-retry:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-ratelimiter:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-timelimiter:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-micrometer:2.1.0'
	implementation 'io.github.resilience4j:resilience4j-core:2.1.0'
	implementation 'io.micrometer:micrometer-registry-prometheus'
