### ISSUE TITLE
Broken tests - CircuitBreakerTest and ReactiveCircuitBreakerTest

### ISSUE THREAD

**Issue by silviobuss** [resilience4j/resilience4j-spring-boot2-demo#9]
Hi @RobWin, all the circuit breaker tests have failed (CircuitBreakerTest and ReactiveCircuitBreakerTest)

![image](https://user-images.githubusercontent.com/51520066/59371720-31771800-8d1c-11e9-986c-040a71e5cf2f.png)

It looks like the circuit is not respecting the waitDurationInOpenState property.

So when these tests are trying to access the success endpoint, the error "o CircuitBreaker 'backendA' is OPEN...." happens.

Do you know what it can be?

**Comment by RobWin** [comment]
Please see #6.
We are fixing it

**Comment by silviobuss** [comment]
Thanks!
